# Generated by Django 3.2 on 2021-07-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_users_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='users',
            name='longitude',
        ),
    ]
