# Generated by Django 3.2 on 2021-07-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_auto_20210714_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='graduates',
            field=models.BooleanField(default=False),
        ),
    ]
