# Generated by Django 3.2 on 2021-07-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_users_graduates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='graduates',
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='1', max_length=20),
        ),
    ]
